#!/usr/bin/env python3
"""Runtime-warning sweep: load areas headless, collect logs, gate on zero.

Runs the existing smoke flags (plus a boot run and a static script/scene
load) with the safe headless drivers, `--debug` (GDScript warnings print
only with it) and engine `--verbose` (leak details). Parses stdout and
stderr, de-duplicates by normalized message, prints a report.

  python tools/bot_warnscan.py --list
  python tools/bot_warnscan.py                       # every area
  python tools/bot_warnscan.py --phases 1,2,6 --report _logs/warnscan/report.txt
  python tools/bot_warnscan.py --areas static,boot --json _logs/warnscan/r.json
  python tools/bot_warnscan.py --areas p3,static --save-baseline _logs/warnscan/base.json  # before a change
  python tools/bot_warnscan.py --areas p3,static --non-leak-diff _logs/warnscan/base.json  # after: NEW/FIXED

--non-leak-diff ignores leak findings (they vary run to run) and ignores the
site, so warnings in moved code are not NEW. Exit 0 if nothing NEW, else 1.

Exit 0: zero warnings, errors and leaks. Exit 1: findings or a failed run
(timeout, crash, nonzero exit). Exit 2: setup or usage problem.
Logs: _logs/warnscan/<area>.{out,err}.txt (gitignored). No game files change.
"""
from __future__ import annotations

import argparse
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from bot_smokes import repo_root, resolve_bin  # noqa: E402
from bot_warnscan_lib import merge, parse_stream, run_failure  # noqa: E402

BOOT_FRAMES = 600
HARNESS = """extends SceneTree
# Generated by tools/bot_warnscan.py. Compiles every script and scene.


func _walk(dir: String, exts: PackedStringArray, out: Array[String]) -> void:
	for f: String in DirAccess.get_files_at(dir):
		if f.get_extension() in exts:
			out.append(dir.path_join(f))
	for d: String in DirAccess.get_directories_at(dir):
		if not d.begins_with("."):
			_walk(dir.path_join(d), exts, out)


func _initialize() -> void:
	var paths: Array[String] = []
	_walk("res://scripts", PackedStringArray(["gd"]), paths)
	_walk("res://scenes", PackedStringArray(["tscn", "tres", "scn"]), paths)
	paths.sort()
	var bad: int = 0
	for p: String in paths:
		if ResourceLoader.load(p) == null:
			bad += 1
			printerr("WARNSCAN: load_failed=", p)
	print("WARNSCAN: loaded=%d failed=%d" % [paths.size(), bad])
	quit(0)
"""


def area_table(floors: list[int], seed: int) -> dict[str, tuple[list[str], str]]:
    """name -> (user args after `--`, description). Insertion order = run order."""
    desc = {
        1: "foundation: boot, player, camera, basic weapon",
        2: "foundation: weapon swap, telegraphs, projectiles",
        3: "dungeon: floor data, doors, stairs, boss flow",
        4: "dungeon: roster, named, flee, pressure",
        5: "dungeon: gather nodes, extract UI, puzzle props",
        6: "camp: artifacts, food, forge, quests",
        7: "dungeon: HUD, pause, debug, recap",
        8: "camp: hub spots, buildings, save backup, archive",
        9: "dungeon: audio, archive catalog, anim models",
    }
    t: dict[str, tuple[list[str], str]] = {}
    for n, d in desc.items():
        t[f"p{n}"] = ([f"--wdb-phase{n}-smoke"], d)
    t["load-timing"] = (["--wdb-load-timing-smoke"], "title -> camp load path")
    t["dungeon-load-timing"] = (["--wdb-dungeon-load-timing-smoke"], "camp -> dungeon enter path")
    for fl in floors:
        t[f"map-f{fl}"] = ([
            "--wdb-dungeon-map-smoke",
            f"--wdb-dungeon-map-seed={seed}",
            f"--wdb-dungeon-map-floor={fl}",
        ], f"dungeon generation dump, seed {seed} floor {fl}")
    t["boot"] = ([], f"[extra launch mode] main scene (splash/title) for {BOOT_FRAMES} frames, no smoke flag")
    t["static"] = ([], "[extra launch mode] --script harness: compile every scripts/**/*.gd and scenes/*.tscn")
    return t


def godot_cmd(exe: Path, root: Path, name: str, uargs: list[str], ns, log_dir: Path) -> list[str]:
    cmd = [str(exe), "--headless", "--display-driver", "headless", "--audio-driver", "Dummy", "--debug"]
    if not ns.no_engine_verbose:
        cmd.append("--verbose")
    if name == "boot":
        cmd += ["--quit-after", str(BOOT_FRAMES)]
    if name == "static":
        cmd += ["--script", str(log_dir / "_static_load.gd")]
    cmd += ["--path", str(root)]
    if uargs:
        cmd += ["--", *uargs]
    return cmd


def run_one(cmd: list[str], out: Path, err: Path, timeout: int) -> tuple[str, int]:
    """Returns (status, returncode). status: ok | timeout | signal."""
    with out.open("w", encoding="utf-8") as so, err.open("w", encoding="utf-8") as se:
        proc = subprocess.Popen(
            cmd, stdin=subprocess.DEVNULL, stdout=so, stderr=se, start_new_session=True,
        )
        try:
            rc = proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            os.killpg(proc.pid, signal.SIGKILL)
            proc.wait()
            return "timeout", -9
    return ("signal" if rc < 0 else "ok"), rc


def pick_areas(ns, table: dict) -> list[str]:
    names: list[str] = []
    if ns.phases:
        names += [f"p{x.strip()}" for x in ns.phases.split(",") if x.strip()]
    if ns.areas:
        names += [x.strip() for x in ns.areas.split(",") if x.strip()]
    if not names:
        return list(table)
    bad = [n for n in names if n not in table]
    if bad:
        raise SystemExit(f"FAIL warnscan: unknown area {','.join(bad)} (see --list)")
    return list(dict.fromkeys(names))


def render(rows: list[tuple], findings: list, ns, secs: float) -> str:
    total = sum(f.count for f in findings)
    out = [f"warnscan areas={len(rows)} repeat={ns.repeat} elapsed={secs:.0f}s", ""]
    out.append(f"{'AREA':<25}{'RESULT':<9}{'SECS':>6}  {'EXIT':<8}FINDINGS")
    for name, status, rc, dt, n in rows:
        out.append(f"{name:<25}{'PASS' if n == 0 else 'FAIL':<9}{dt:>6.1f}  {status if status != 'ok' else rc!s:<8}{n}")
    out += ["", f"FINDINGS unique={len(findings)} total={total}"]
    order = sorted(findings, key=lambda f: (f.kind, -f.count))
    for i, f in enumerate(order, 1):
        areas = ",".join(f"{a}x{c}" if c > 1 else a for a, c in f.areas.items())
        out.append(f"\n[{i}] {f.kind}  x{f.count}  areas: {areas}")
        out.append(f"    {f.samples[0] if f.samples else f.msg}")
        for extra in f.samples[1:]:
            out.append(f"    also: {extra}")
        if f.site:
            out.append(f"    site: {f.site}")
        out.append(f"    first: {f.first}")
        if f.hint:
            out.append(f"    hint: {f.hint}")
        for s in f.stack[: (8 if ns.verbose else 4)]:
            out.append(f"    | {s.strip()}")
    out.append(f"\nRESULT={'PASS' if not findings else 'FAIL'} unique={len(findings)} total={total}")
    return "\n".join(out) + "\n"


def non_leak_rows(findings: list) -> list[dict]:
    return [{"kind": f.kind, "norm": f.norm, "site": f.site, "areas": sorted(f.areas)}
            for f in findings if f.kind != "leak"]


def diff_rows(cur: list[dict], base: list[dict]) -> tuple[list[dict], list[dict]]:
    """NEW and FIXED rows by (kind, norm) count; sites only pick which row to show."""
    def split(rows):
        d: dict = {}
        for r in rows:
            d.setdefault((r["kind"], r["norm"]), []).append(r)
        return d
    c, b = split(cur), split(base)
    new, fixed = [], []
    for k in sorted(set(c) | set(b)):
        cs, bs = c.get(k, []), b.get(k, [])
        bsites = {r["site"] for r in bs}
        csites = {r["site"] for r in cs}
        n = len(cs) - len(bs)
        if n > 0:
            pick = [r for r in cs if r["site"] not in bsites] or cs
            new += pick[:n]
        elif n < 0:
            pick = [r for r in bs if r["site"] not in csites] or bs
            fixed += pick[:-n]
    return new, fixed


def main() -> int:
    p = argparse.ArgumentParser(description="Headless runtime-warning sweep (zero-warning gate)")
    p.add_argument("--list", action="store_true", help="list areas and exit")
    p.add_argument("--areas", default="", help="comma list of area names (see --list)")
    p.add_argument("--phases", default="", help="shorthand for smoke phases, e.g. 1,2,6")
    p.add_argument("--map-floors", default="1", help="dungeon-map floors to sweep (default 1)")
    p.add_argument("--map-seed", type=int, default=42)
    p.add_argument("--timeout", type=int, default=90, help="seconds per run")
    p.add_argument("--repeat", type=int, default=1, help="runs per area (leaks can vary run to run)")
    p.add_argument("--no-engine-verbose", action="store_true", help="drop Godot --verbose (no leak detail rows)")
    p.add_argument("--report", default="", help="also write the text report here")
    p.add_argument("--json", default="", help="write findings as JSON here")
    p.add_argument("--save-baseline", default="", help="write non-leak findings JSON here (run before a change)")
    p.add_argument("--non-leak-diff", default="", help="compare non-leak findings to a --save-baseline file; exit 1 if NEW")
    p.add_argument("--verbose", action="store_true", help="print commands and longer stacks")
    ns = p.parse_args()
    root = repo_root()
    floors = [int(x) for x in ns.map_floors.split(",") if x.strip()]
    table = area_table(floors, ns.map_seed)
    if ns.list:
        for name, (uargs, d) in table.items():
            print(f"{name:<22}{d}")
        print("\nAll areas run by default. 'extra launch modes' are not --wdb smoke flags;")
        print("they await user approval and can be skipped by naming --areas/--phases.")
        return 0
    exe = resolve_bin()
    if exe is None:
        print("FAIL warnscan: no Godot binary; run python tools/bot_smokes.py --setup")
        return 2
    names = pick_areas(ns, table)
    log_dir = root / "_logs" / "warnscan"
    log_dir.mkdir(parents=True, exist_ok=True)
    for old in log_dir.glob("*.txt"):
        old.unlink()
    (log_dir / "_static_load.gd").write_text(HARNESS, encoding="utf-8", newline="\n")
    merged: dict = {}
    rows: list[tuple] = []
    t0 = time.time()
    for name in names:
        uargs = table[name][0]
        cmd = godot_cmd(exe, root, name, uargs, ns, log_dir)
        for r in range(ns.repeat):
            tag = name if ns.repeat == 1 else f"{name}.r{r + 1}"
            out, err = log_dir / f"{tag}.out.txt", log_dir / f"{tag}.err.txt"
            if ns.verbose:
                print("run\t" + " ".join(cmd), flush=True)
            ts = time.time()
            status, rc = run_one(cmd, out, err, ns.timeout)
            found = []
            for stream, path in (("out", out), ("err", err)):
                found += parse_stream(path.read_text(encoding="utf-8", errors="replace"), name, stream)
            if status == "timeout":
                found.append(run_failure(name, f"timeout after {ns.timeout}s (process group killed)"))
            elif status == "signal":
                found.append(run_failure(name, f"killed by signal {-rc}"))
            elif rc != 0:
                found.append(run_failure(name, f"nonzero exit {rc}"))
            merge(merged, found)
            rows.append((tag, status, rc, time.time() - ts, len(found)))
            print(f"{tag}\t{'PASS' if not found else 'FAIL'}\tfindings={len(found)}", flush=True)
    text = render(rows, list(merged.values()), ns, time.time() - t0)
    print("\n" + text)
    if ns.report:
        Path(ns.report).parent.mkdir(parents=True, exist_ok=True)
        Path(ns.report).write_text(text, encoding="utf-8")
    if ns.json:
        Path(ns.json).parent.mkdir(parents=True, exist_ok=True)
        data = [{"kind": f.kind, "message": f.msg, "site": f.site, "count": f.count,
                 "areas": f.areas, "first": f.first, "hint": f.hint, "stack": f.stack}
                for f in merged.values()]
        Path(ns.json).write_text(json.dumps(data, indent=2), encoding="utf-8")
    rows_now = non_leak_rows(list(merged.values()))
    if ns.save_baseline:
        Path(ns.save_baseline).parent.mkdir(parents=True, exist_ok=True)
        Path(ns.save_baseline).write_text(json.dumps(rows_now, indent=2), encoding="utf-8")
        print(f"baseline saved: {len(rows_now)} non-leak findings -> {ns.save_baseline}")
    if ns.non_leak_diff:
        base = json.loads(Path(ns.non_leak_diff).read_text(encoding="utf-8"))
        new, fixed = diff_rows(rows_now, base)
        for tag, rs in (("NEW", new), ("FIXED", fixed)):
            for r in rs:
                print(f"{tag}\t{r['kind']}\t{r['site'] or '-'}\t{r['norm'][:110]}")
        print(f"non-leak-diff: baseline={len(base)} now={len(rows_now)} new={len(new)} fixed={len(fixed)}")
        return 0 if not new else 1
    return 0 if not merged else 1


if __name__ == "__main__":
    sys.exit(main())
