extends Object

## Values categories and key -> category rules. First matching prefix wins; no match is "Other".
## Left column is the first half of CATS (player, combat, enemies); right is world and economy.

const CATS: Array[String] = [
	"Player",
	"Movement",
	"Combat",
	"Cover",
	"Aim & Lock",
	"Adrenaline",
	"Great Axe",
	"Staff",
	"Bow",
	"Enemy Melee Stats",
	"Enemy Ranged Stats",
	"Enemy AI",
	"Enemy Spawns",
	"Level Scaling",
	"Dungeon Layout",
	"Gathering & Props",
	"Camera",
	"Ground",
	"Lighting",
	"XP & Skills",
	"Gear",
	"Set Bonuses",
	"Forge & Affixes",
	"Loot & Drops",
	"Shops & Quests",
	"Consumables",
	"Other",
]

const RULES: Array = [
	["player_", "Player"],
	["near_death_hp", "Player"],
	["move_", "Movement"],
	["dash_", "Movement"],
	["attack_move_mult", "Movement"],
	["crit_cover", "Cover"],
	["cover_", "Cover"],
	["aim_line_", "Aim & Lock"],
	["lock_stick_", "Aim & Lock"],
	["adrenaline_", "Adrenaline"],
	["axe_", "Great Axe"],
	["slam_", "Great Axe"],
	["staff_", "Staff"],
	["bow_", "Bow"],
	["arrow_", "Bow"],
	["e_archer_", "Enemy Ranged Stats"],
	["e_shaman_", "Enemy Ranged Stats"],
	["e_imp_", "Enemy Ranged Stats"],
	["e_wisp_", "Enemy Ranged Stats"],
	["e_", "Enemy Melee Stats"],
	["enemy_cl_", "Level Scaling"],
	["cl_", "Level Scaling"],
	["cycle_hp", "Level Scaling"],
	["enemy_gear_", "Loot & Drops"],
	["enemy_gold_", "Loot & Drops"],
	["enemy_hp_mult", "Enemy Spawns"],
	["enemy_dmg_mult", "Enemy Spawns"],
	["enemy_speed_mult", "Enemy Spawns"],
	["named_", "Enemy Spawns"],
	["boss_hp_mult", "Enemy Spawns"],
	["ambush_", "Enemy Spawns"],
	["pressure_", "Enemy Spawns"],
	["base_guards", "Enemy Spawns"],
	["enemy_", "Enemy AI"],
	["leash_", "Enemy AI"],
	["hunt_", "Enemy AI"],
	["reaggro_", "Enemy AI"],
	["aggro_", "Enemy AI"],
	["flee_", "Enemy AI"],
	["idle_timer", "Enemy AI"],
	["noreveal_", "Enemy AI"],
	["los_period", "Enemy AI"],
	["sep_max", "Enemy AI"],
	["windup_", "Enemy AI"],
	["hop_height", "Enemy AI"],
	["fly_height", "Enemy AI"],
	["gen_", "Dungeon Layout"],
	["hall_", "Dungeon Layout"],
	["room_pack", "Dungeon Layout"],
	["outline_", "Dungeon Layout"],
	["crystal_", "Dungeon Layout"],
	["fog_radius", "Dungeon Layout"],
	["max_clerks", "Dungeon Layout"],
	["ghost_shop_chance", "Dungeon Layout"],
	["mine_", "Gathering & Props"],
	["wood_", "Gathering & Props"],
	["skill_gather", "Gathering & Props"],
	["tool_gather", "Gathering & Props"],
	["break_count", "Gathering & Props"],
	["break_orb", "Gathering & Props"],
	["crack_hp", "Gathering & Props"],
	["shrine_", "Gathering & Props"],
	["campfire_count", "Gathering & Props"],
	["cam_", "Camera"],
	["look_", "Camera"],
	["ground_", "Ground"],
	["light_", "Lighting"],
	["xp_keep", "XP & Skills"],
	["xp_", "XP & Skills"],
	["skill_", "XP & Skills"],
	["gear_", "Gear"],
	["set_", "Set Bonuses"],
	["forge_", "Forge & Affixes"],
	["affix_", "Forge & Affixes"],
	["break_gold", "Loot & Drops"],
	["boss_", "Loot & Drops"],
	["chest_", "Loot & Drops"],
	["shop_", "Shops & Quests"],
	["vendor_", "Shops & Quests"],
	["restock_", "Shops & Quests"],
	["snack_cost", "Shops & Quests"],
	["art_cost", "Shops & Quests"],
	["pawn_gold", "Shops & Quests"],
	["quest_", "Shops & Quests"],
	["potion_", "Consumables"],
	["food_", "Consumables"],
	["bag_cap", "Consumables"],
	["snack_heal", "Consumables"],
	["campfire_heal", "Consumables"],
	["orb_heal", "Consumables"],
	["special_", "Combat"],
	["crit_", "Combat"],
	["knockback", "Combat"],
	["hitstop", "Combat"],
	["defense_k", "Combat"],
	["dummy_", "Combat"],
	["atk_fps", "Combat"],
	["trail_", "Combat"],
	["pierce_stop", "Combat"],
	["glance_float_a", "Combat"],
]

static func cat_of(name: String) -> String:
	var n: String = name.to_lower()
	for r in RULES:
		if n.begins_with(str(r[0])):
			return str(r[1])
	return "Other"
